/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team3.initial.main;

import java.awt.event.ActionListener;
import team3.initial.swing.*;

/**
 *
 * @author RAVEN
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
    }

    public void register() {
        txtUser.grabFocus();
    }

    public void addEventBackLogin(ActionListener event) {
        register.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser = new team3.initial.swing.MyTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new team3.initial.swing.MyPassword();
        register = new team3.initial.swing.MyButton();
        txtUser2 = new team3.initial.swing.MyTextField();
        txtUser3 = new team3.initial.swing.MyTextField();
        txtUser4 = new team3.initial.swing.MyTextField();
        firstname = new javax.swing.JLabel();
        firstname1 = new javax.swing.JLabel();
        firstname2 = new javax.swing.JLabel();
        firstname3 = new javax.swing.JLabel();
        firstname4 = new javax.swing.JLabel();
        firstname5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 249, 255));
        setPreferredSize(new java.awt.Dimension(1393, 855));

        txtUser.setForeground(new java.awt.Color(51, 51, 51));
        txtUser.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        txtUser.setMinimumSize(new java.awt.Dimension(400, 28));
        txtUser.setPreferredSize(new java.awt.Dimension(10, 43));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 115, 155));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRATION FORM");

        txtPass.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        txtPass.setPreferredSize(new java.awt.Dimension(10, 43));

        register.setBackground(new java.awt.Color(50, 115, 155));
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Register");
        register.setColor(new java.awt.Color(50, 115, 155));
        register.setColorOver(new java.awt.Color(50, 115, 155));
        register.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        txtUser2.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        txtUser2.setPreferredSize(new java.awt.Dimension(400, 43));
        txtUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUser2ActionPerformed(evt);
            }
        });

        txtUser3.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        txtUser3.setPreferredSize(new java.awt.Dimension(400, 43));
        txtUser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUser3ActionPerformed(evt);
            }
        });

        txtUser4.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        txtUser4.setPreferredSize(new java.awt.Dimension(10, 43));
        txtUser4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUser4ActionPerformed(evt);
            }
        });

        firstname.setFont(new java.awt.Font("Arial Narrow", 1, 25)); // NOI18N
        firstname.setForeground(new java.awt.Color(51, 51, 51));
        firstname.setText("Middle Name");

        firstname1.setFont(new java.awt.Font("Arial Narrow", 1, 25)); // NOI18N
        firstname1.setForeground(new java.awt.Color(51, 51, 51));
        firstname1.setText("First Name");

        firstname2.setFont(new java.awt.Font("Arial Narrow", 1, 25)); // NOI18N
        firstname2.setForeground(new java.awt.Color(51, 51, 51));
        firstname2.setText("Last Name");

        firstname3.setFont(new java.awt.Font("Arial Narrow", 1, 25)); // NOI18N
        firstname3.setForeground(new java.awt.Color(51, 51, 51));
        firstname3.setText("Password");

        firstname4.setFont(new java.awt.Font("Arial Narrow", 1, 25)); // NOI18N
        firstname4.setForeground(new java.awt.Color(51, 51, 51));
        firstname4.setText("Username");

        firstname5.setFont(new java.awt.Font("Arial Narrow", 1, 25)); // NOI18N
        firstname5.setForeground(new java.awt.Color(51, 51, 51));
        firstname5.setText("Date Hired");

        jDateChooser1.setDateFormatString("MM / d / yy");
        jDateChooser1.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\STREAMTIMM\\Downloads\\BG.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(firstname1)
                .addGap(309, 309, 309)
                .addComponent(firstname)
                .addGap(288, 288, 288)
                .addComponent(firstname2))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(firstname4)
                .addGap(316, 316, 316)
                .addComponent(firstname3)
                .addGap(318, 318, 318)
                .addComponent(firstname5))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstname1)
                    .addComponent(firstname)
                    .addComponent(firstname2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstname4)
                    .addComponent(firstname3)
                    .addComponent(firstname5))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser2ActionPerformed

    private void txtUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUser3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser3ActionPerformed

    private void txtUser4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUser4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser4ActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel firstname1;
    private javax.swing.JLabel firstname2;
    private javax.swing.JLabel firstname3;
    private javax.swing.JLabel firstname4;
    private javax.swing.JLabel firstname5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private team3.initial.swing.MyButton register;
    private team3.initial.swing.MyPassword txtPass;
    private team3.initial.swing.MyTextField txtUser;
    private team3.initial.swing.MyTextField txtUser2;
    private team3.initial.swing.MyTextField txtUser3;
    private team3.initial.swing.MyTextField txtUser4;
    // End of variables declaration//GEN-END:variables
}
