
Panel.background=#acdfff
//Header.background=#32739B

Toast.success.outlineColor=#4caf50
Toast.info.outlineColor=#03a9f4
Toast.warning.outlineColor=#ff9800
Toast.error.outlineColor=#ef5350

defaultFont = 14 Roboto, Arial

# headings
h00.font = +24
h0.font = +18
h1.font = +12 $semibold.font
h2.font = +6 $semibold.font
h3.font = +3 $semibold.font
h4.font = bold

h1.regular.font = +12
h2.regular.font = +6
h3.regular.font = +3

# text
large.font = +2
medium.font = -1
small.font = -2
mini.font = -3

